name: "Clear Infrastructure"
on:
  workflow_dispatch:

permissions: # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0

      - name: Terraform Init
        working-directory: ./infrastructure
        run : terraform init -backend-config="backend.tfvars"

      - name: Terraform Destroy
        working-directory: ./infrastructure
        run: terraform destroy -input=false -auto-approve
